data:
  his_size: 50
  data_format: news
  npratio: 4
  flatten_article: False
  body_shape:
    - 1
    - 30
  news_attr:
    title:
      - 30

info:
  metrics:
  - group_auc
  - mean_mrr
  - ndcg@5;10
  show_step: 100000

model:
  model_name: NRHABody
  attention_hidden_dim: 200
  word_emb_dim: 300
  kernel_size: 3
  dropout: 0.2
  head_num: 20
  head_dim: 20
  model_type: nrha_body
  embedding: "word2vec"

train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.0001
  loss: cross_entropy_loss
  optimizer: adam
  support_quick_scoring: true
