data:
  his_size: 50
  data_format: news
  npratio: 4

  news_attr:
    title:
      - 30

info:
  metrics:
  - group_auc
  - mean_mrr
  - ndcg@5;10
  show_step: 100000
  
model:
  attention_hidden_dim: 200
  word_emb_dim: 300
  dropout: 0.2
  head_num: 10
  head_dim: 30
  model_type: nrha
  embedding: "word2vec"

  gru_type: AUGRU
  att_hidden_layers:
    - 80
    - 40
  att_dropout: 0
  activation: prelu

  kernel_size: 3

train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.0001
  loss: cross_entropy_loss
  optimizer: adam
  support_quick_scoring: true
